spring:
  datasource:
    url: jdbc:mysql://ssr.sady.vip:3306/mybatis?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: admin
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      ###逻辑未删除的值
      logic-not-delete-value: 0
      ###逻辑已删除的值
      logic-delete-value: 1

##增加日志输出，方便定位问题
logging:
  level:
    root : warn
    com.springboot.dao: trace
  ###控制台输出格式
  pattern:
    console: '%p%m%n'


