spring:
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
  datasource:
#    url: jdbc:mysql://ssr.sady.vip:3306/mybatis?serverTimezone=UTC
#    username: root
#    password: 123456

    url: jdbc:mysql://data.thsware.com:3306/ths_productdata_back?serverTimezone=UTC
    username: root
    password: ths#db#mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: admin
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      ###逻辑未删除的值
      logic-not-delete-value: 0
      ###逻辑已删除的值
      logic-delete-value: 1

##增加日志输出，方便定位问题
logging:
  level:
    root : info
#    com.springboot.dao: trace
  ###控制台输出格式
  pattern:
    console: '%p%m%n'
