# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 持续集成测试项目

on:
  push:
    branches: master
    
jobs:
  编译和部署到远程:
    runs-on: ubuntu-latest
    steps:
    - name: 检出最新代码
    - uses: actions/checkout@v2
    - name: 设置JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
      #通过ssh上传文件工具
    - name: 安装sshpass
      run: sudo apt-get install sshpass
      
    - name: 使用Maven编译
      run: mvn -B package --file web/pom.xml
      
    - name: SCP Files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "/*.*,/root/"
        target: "test"
  编译和部署到远程1:
    runs-on: ubuntu-latest



