# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 持续集成测试项目

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 设置JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
      #通过ssh上传文件工具
    - name: 安装sshpass
      run: sudo apt-get install sshpass
      
    - name: 使用Maven编译
      run: mvn -B package --file web/pom.xml
      
    - name: SCP Files
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.PASSWORD }}
        port: 28188
        source: "/home/runner/work/springboot/springboot/web/target/"
        target: "target"
  send-Notice:
    runs-on: ubuntu-latest
    steps:
      - name: 发送邮件通知
        uses: dawidd6/action-send-mail@v2.3.0
        with:
          # SMTP server address
          server_address:mail.thsware.com
          # SMTP server port
          server_port:25
          # Authenticate as this user to SMTP server
          username:wanglu@thsware.com
          # Authenticate with this password to SMTP server
          password:1qaz2wsx..
          # Subject of mail message
          subject:GitHubActionNotice
          # Body of mail message (might be a filename prefixed with file:// to read from)
          body:你好,消息测试！！！！！！！！！！！！！
          # Recipients mail addresses (separated with comma)
          to:thsware2020@gmail.com
          # Full name of mail sender (might be with an email address specified in <>)
          from:wanglu@thsware.com
          # Content-Type HTTP header (text/html or text/plain)
          content_type: # optional, default is text/plain
          # Convert body from Markdown to HTML (set content_type input as text/html too)
          convert_markdown: # optional
          # Files that will be added to mail message attachments (separated with comma)
          attachments: # optional


