# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: 持续集成测试项目

on:
  push:
    branches: master
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: 设置JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: 使用Maven编译
      run: mvn -B package --file web/pom.xml
    - name: Deploy
      uses: saltbo/uptoc@master
      with:
        driver: qiniu
        region: cn-east-1
        bucket: warlue
        exclude: .cache,test
        dist: public
      env:
        UPTOC_UPLOADER_AK: ${{ secrets.UPTOC_UPLOADER_KEYID }}
        UPTOC_UPLOADER_SK: ${{ secrets.UPTOC_UPLOADER_KEYSECRET }}
